name: Publish
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Running pip install
        run: pip install -r requirements/build.txt

      - name: Building
        run: python -m build